salesforce_assignment/AssignmentWebService/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_assignment/AssignmentWebService/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY() - DOB__c)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Student_In_Class</relationshipLabel>
        <relationshipName>Student_In_Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_assignment/AssignmentWebService/classes/StudentSiteController.cls
public class StudentSiteController {
    
    public static List<Student__c> stdList{ get; private set;}
    
    public static Student__c stdDetail{ get; set;}
    
    public StudentSiteController (){
    }
    public static  List<SelectOption> selectList { get{
        stdList = new List<Student__c> ([SELECT Id,Name FROM Student__c]);
        selectList = new List<SelectOption> ();
        for(Student__c std : stdList) {
            selectList.add(new SelectOption(std.Id,std.Name));
        }
        return selectList;
    } set;}
    
    @RemoteAction
    public static Student__c getStudent( Id selectedId ){
        stdDetail = [SELECT Id , Name ,First_Name__c , LastName__c , age__c, Class__c ,DOB__c FROM Student__c WHERE Id =:selectedId] ;
        system.debug(stdDetail);
        return stdDetail ;
        
    }
    
}