salesforce_assignment/AssignmentWebService/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_assignment/AssignmentWebService/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Student_In_Class</relationshipLabel>
        <relationshipName>Student_In_Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_assignment/Assignment3/src/classes/StudentClass.cls
public class StudentClass {
    Public Static List<Student__c> getAllStudentINClass(Id classId) {
        List<Student__c> allStudentInClass = new List<Student__c>();
        allStudentInClass = [Select id ,Name from Student__c where class__r.ID = :classId];
        return allStudentInClass;
    }
    
    Public Static Map<Id, Set<Student__C>> getAllClassWithStudents() {
        Map<Id, Set<Student__C>> classWithStudentMap = new Map<Id, Set<Student__C>>();
        List<Class__c> classWithStudentList = new List<Class__c>([SELECT Id, (SELECT Name FROM Student_In_Class__r) FROM Class__c]);
        for(Class__c Class1 : classWithStudentList) {
            classWithStudentMap.put(Class1.Id, new Set<Student__c>(Class1.Student_In_Class__r));
        }
        return classWithStudentMap;
    }
}