salesforce_assignment/AssignmentEmail/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_assignment/Assignment3/src/classes/OpportunityController.cls
public class OpportunityController {

    public static void populateInOpportunity(List<Opportunity> oppList) {
     
        for(SObject opp:oppList){
            if(opp instanceof Opportunity) {
                Opportunity opportunity=(Opportunity)opp;
                if(opportunity.BillToContact__c != null && opportunity.Manager__c == null)
                {
                    opportunity.Manager__c =opportunity.AccountId;
                }
            }
            
        }
     
    }
}