salesforce_assignment/VF2Assignment/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablets</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

salesforce_assignment/VF2Assignment/src/objects/PurchaseOrder__c.object
<CustomObject>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_assignment/VF2Assignment/src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>ProductCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_assignment/VF2Assignment/src/classes/ShoppingController.cls
public class ShoppingController {
    
    public  List <product2> products { get; set; }
    
    public  Id orderId {get;set;}
    
    public String idOfProductToAdd {get;set;}
    
    public String idOfProductToRemove {get;set;}
    
    public String SelectedCategory { get; set; }
    
    public List<PurchaseOrderLineItem__c> items {
        get
        {
            List<PurchaseOrderLineItem__c> item = ShoppingService.searchItems(orderId);
        	return item;
        }
        set;}
    
    public List<SelectOption> Category
    {
        get
        {
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = product2.category__c .getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            
            return options;
        }
    }
    
    public ShoppingController(ApexPages.StandardController controller)
    { 
        orderId = System.currentPageReference().getParameters().get('id');
    }
    
    public  void populateProduct()
    {
        products = ShoppingService.populateProduct(SelectedCategory);
        system.debug(products);
    }
    
    public void RemoveFromCart()
    {
        List <PurchaseOrderLineItem__c> product = ShoppingService.searchProductToRemove(idOfProductToRemove);
        PurchaseOrderLineItem__c getProduct;
        if(product.size()>0)
        {
            getProduct=product.get(0);
        }
        delete getProduct;
    }
    
    public void AddToCart()
    { 
        List<PurchaseOrderLineItem__c> ListItems; 
        
        List<product2> product = ShoppingService.searchProductToAdd(idOfProductToAdd);
        
        Product2 getProduct;
        PurchaseOrderLineItem__c PurchaseOrder;
        
        if(product.size()>0)
        {
            getProduct=product.get(0);
        }
        ListItems = ShoppingService.selectItemListFromPurchaseOrderLineItem(getProduct, orderId);
        
        if(ListItems.size()>0)
        {				
            PurchaseOrder=ListItems.get(0);
            PurchaseOrder.Quantity__c+=1;
            update PurchaseOrder;
        }    
        else
        {
            PurchaseOrder =new PurchaseOrderLineItem__c(name=getProduct.name,price__c=getProduct.Price__c,ProductCode__c=getproduct.ProductCode,Quantity__c = 1,Product__c=getProduct.id,PurchaseOrder__c = orderId);
            insert PurchaseOrder;
        }
    }
    
}