salesforce_assignment/VF2Assignment/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablets</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

salesforce_assignment/VF2Assignment/src/objects/PurchaseOrder__c.object
<CustomObject>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_assignment/VF2Assignment/src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>ProductCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <formula>Price__c *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_assignment/VF2Assignment/src/classes/ShoppingSelector.cls
public class ShoppingSelector {

    public static List<PurchaseOrderLineItem__c> searchItems (Id orderId)
    {
        List<PurchaseOrderLineItem__c> item = [select ID,ProductCode__c,Name,Price__c,Quantity__c,TotalPrice__c from PurchaseOrderLineItem__c where PurchaseOrder__c =: orderId];
        return item;
    }
    
    public static List <product2> populateProduct (String SelectedCategory)
    {
        List<product2> products = [select Id,ProductCode,Name,Price__c,category__c from product2 where category__c =:SelectedCategory];
        return products;
    }
    
    public static List<PurchaseOrderLineItem__c> searchProductToRemove(String idOfProductToRemove)
    {
        List<PurchaseOrderLineItem__c> product = [select ID,name from PurchaseOrderLineItem__c where ID =:idOfProductToRemove Limit 1];
        return product;
    }
    
    public static List<product2> searchProductToAdd(String idOfProductToAdd)
    {
        List<product2> product = [select ID,name,Price__c,ProductCode from product2 where ID =:idOfProductToAdd Limit 1];
        return product;
    }
    
    public static List<PurchaseOrderLineItem__c> selectItemListFromPurchaseOrderLineItem(Product2 getProduct, Id orderId)
    {
        List<PurchaseOrderLineItem__c> listItems = [select ID,name,Quantity__c,Price__c,TotalPrice__c from PurchaseOrderLineItem__c where Product__r.id =:getProduct.id and purchaseOrder__c =:orderId Limit 1];
        return listItems;
    }
}